### ISSUE TITLE
Missed use statement

### ISSUE THREAD

**Issue by saingal** [prooph/docs#1]
https://github.com/prooph/docs/blob/c6a5cca6c9c496c9687d15ccbc4c355f4a64569c/docs/tutorial/testing_aggregates.html#L936

Missed use App\Basket\Model\Event\ProductAddedToBasket

**Comment by prolic** [comment]
Submit a PR please

**Comment by saingal** [comment]
ok. check please PR

**Comment by prolic** [comment]
thx
